# Generated by Django 5.0.6 on 2024-05-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_startswith', models.IntegerField()),
                ('code', models.IntegerField()),
                ('numbers_from', models.IntegerField()),
                ('numbers_to', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('operator', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('gar_region', models.CharField(max_length=255)),
                ('inn', models.IntegerField()),
            ],
        ),
    ]
