# Generated by Django 5.0.6 on 2024-05-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0002_alter_range_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='range',
            name='inn',
            field=models.BigIntegerField(null=True),
        ),
    ]
