# Generated by Django 5.0.6 on 2024-05-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0003_alter_range_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='range',
            name='region',
            field=models.CharField(max_length=600),
        ),
    ]
