# Generated by Django 5.0.6 on 2024-05-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0004_alter_range_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='range',
            name='gar_region',
            field=models.CharField(max_length=600),
        ),
    ]
