# Generated by Django 5.0.6 on 2024-05-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0005_alter_range_gar_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='range',
            name='gar_region',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='range',
            name='region',
            field=models.CharField(max_length=2000),
        ),
    ]
